// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/niko-cb/uct/internal/application/usecase"
	"github.com/niko-cb/uct/internal/controller"
	"github.com/niko-cb/uct/internal/domain/service"
	"github.com/niko-cb/uct/internal/infrastructure/gateway"
	"github.com/niko-cb/uct/internal/infrastructure/persistent/mysql"
	"github.com/niko-cb/uct/internal/infrastructure/persistent/mysql/transaction"
	"github.com/niko-cb/uct/internal/infrastructure/web/config"
	"github.com/niko-cb/uct/internal/infrastructure/web/handler"
)

// Injectors from wire.go:

func InitializeInvoiceHandler(cfg *config.Config) handler.IInvoiceHandler {
	mySQLClient := mysql.NewMySQLClient(cfg)
	invoiceRepository := gateway.NewInvoiceGateway(mySQLClient)
	invoiceService := service.NewInvoiceService(invoiceRepository)
	repositoryTransaction := transaction.NewTransaction(mySQLClient)
	invoiceUsecase := usecase.NewInvoiceUsecase(invoiceService, repositoryTransaction)
	invoiceController := controller.NewInvoiceController(invoiceUsecase)
	iInvoiceHandler := handler.NewInvoiceHandler(invoiceController)
	return iInvoiceHandler
}
